### ISSUE TITLE
Before MVP - Claiming a profile - logging in for the first time

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#12]
When you have updated your information and bank details, once clicking to complete the transaction, it should take the user to their account, but instead it pulls you to the home page. Can you set it up to take the user to their profile to begin personalizing?

**Comment by gitKendra** [comment]
I have it set now so that anytime a user logs in, it automatically takes them to their "Details" page.

**Comment by idowling1007** [comment]
Hey Kendra, this is linked to the issue I created today - #23 about the error screen. When I completed the information to create the account, I got the following message.

![image](https://user-images.githubusercontent.com/61845027/76332369-ad5fba00-62c6-11ea-9982-ab76f528e83d.png)
