### ISSUE TITLE
Before MVP - updating profile - Education and Qualifications

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#16]
The different schooling sections from Primary Education and Additional Qualifications have different wording for the date. I think that these should all say "year graduated", and have a drop down for the year.

When Selecting the Specialties, modalities, etc, is it possible to change the golden trashcans next to the selections, and replace them with a simple red x or a subtle grey worded "Delete?" or "Remove?"

![image](https://user-images.githubusercontent.com/61845027/76027576-dc5ce100-5efe-11ea-93b1-0f1c28cbf12a.png)

Also can you change the selection process from one drop down where you can select multiple options, instead of having 2 pop ups? 

![image](https://user-images.githubusercontent.com/61845027/76028217-1f6b8400-5f00-11ea-8edb-038bfb553a53.png)

**Comment by gitKendra** [comment]
Partially complete. still has popup dialog for selecting items
