### ISSUE TITLE
Before MVP - Updating Profile - Saving information

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#17]
The only things that are allowing me to save are:
1 - Profile Picture
2 - Gender
3 - Name
4 - Business Name
5 - About me information.

Everything else goes away.

**Comment by gitKendra** [comment]
My top priority is getting the rest of the update profile functional. Then will focus on more of the UI and adding actual values to the input list

I just pushed an update that should allow you to update the Personal Info page in it's entirety. Next big push will be the Business Info page

**Comment by gitKendra** [comment]
Business info now updates. Will be available on next deploy
