### ISSUE TITLE
Medium - Claiming profile - needing manual process, notice needed for what is needed to be approved

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#39]
When therapists need the manual process to get approved, we need to have a pop up with what is required before taking them to the "contact us" page.

**Comment by gitKendra** [comment]
@idowling1007 What information should be displayed on the popup?

**Comment by idowling1007** [comment]
Hey Kendra, when someone is going to manually claim their profile, we would need to have the link to the page that they are claiming, along with the information on what they need to send us. Otherwise we are going to get a copy of the documentation, and we would have to manually search for them on our end, which seems silly. We would also need to have the option to attach the documentation via the contact us page for this reason. 

So - I would find my page, and click the claim profile link. As soon as I hit the "I no longer have access to those verification methods" and hit submit, on the contact us page, it should automatically link the profile that I am attempting to claim, and give me the option to add an attachment of the documentation I need to send. That will be sent to a queue where the attachment will be reviewed and we will confirm or deny, and send them back a reply with the next steps.

This will be the information that the therapist will see when they are about to contact us:

“Please provide an email address, and upload supporting documentation to validate that your identification matches the licensed name.  A copy of your driver’s license is required where the driver’s license name matches the current profile/licensed therapist name.

Once we have had an opportunity to validate the documentation provided, we will contact you with how to proceed. Response time is usually within 72 hours."
