### ISSUE TITLE
SUPER HIGH - When logged in, it does not allow you to go to your profile and make changes

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#45]
Per my email last week, I went through the 'forgot password' process. 

When I got the email, the link took about 90 seconds to load up the information for the new PW entry. 

After updating the PW, when I log in, it is not taking me to the profile page, and in the top right, when I click the icon, it only allows me to log off. 

![image](https://user-images.githubusercontent.com/61845027/80320605-5a45b600-87e5-11ea-8555-03d47b231861.png)

The links to edit the profile is missing from before.

**Comment by KC135Q** [comment]
OK - this is for the admin account, not a Licensed Therapist account. Your users will not see any of this and we will update the demo accounts so you can see what they see.

**Comment by KC135Q** [comment]
Previous statement was most likely incorrect. Unable to duplicate unless I sign in to review using SSO and forget to sign out.
