### ISSUE TITLE
Medium - Search Results

### ISSUE THREAD

**Issue by KC135Q** [idowling1007/therapy-reviews#50]
5 - With the number of accounts per page, can we remove the options for 5 and 10, and have it instead offer 25, 50, and 'Show All'?
6 - When I start a new search after, for example, looking for a zip code, and then a specific name, it should reset the search back to the first. In this case, I searched for zip code 32765, and got to about 75-100 on the therapist count before I typed in a name. Instead of bringing the search back to #1, it kept me in the same place, and I had to hit the left arrow to go back to the beginning:

**Comment by idowling1007** [comment]
Closing this. Confirmed updates on site.
