### ISSUE TITLE
high - Links Inop

### ISSUE THREAD

**Issue by KC135Q** [idowling1007/therapy-reviews#56]
the links at the bottom of the site to the terms and conditions, as well as the privacy policy are not working on the site. Are you working on that part of the site? If not, can you correct that so that the links are working again :slightly_smiling_face: Many thanks to you both

**Comment by gitKendra** [comment]
Links are currently working on therapyreviews.com and on local.

**Comment by gitKendra** [comment]
I am making the cursor show like the text is clickable for UI
