### ISSUE TITLE
High - Search bar not working fully.

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#57]
Hey guys, 

I had one of my contacts checking the site who has the last name "Parker", and he said that when he searched his last name, it pulled up nothing related to that request. If there are no Parkers on the list, then it should reflect a "There are no results found with [insert request here]"

I checked the data, and there should be at least 4 Parkers on the list that should have pulled up. 

This is a high priority as we need to have the search working accurately. 

Thank you so much for all you guys do,

Ian

**Comment by idowling1007** [comment]
Hey @KC135Q & @gitKendra 2 things with this one. 
1 - The search options should not be pulling up a street address at all. We should only have 3 things pulled up. Name, City or Zip. Anything else being pulled up should not happen. It should pull name first and then city.
2 - In the search bar, it already shows "Search by name and city" as search parameters, but can you change that to say "Search by Name, City or Zip"?

**Comment by KC135Q** [comment]
Take street address out of the search:
- Name, City or Zip.

**Comment by KC135Q** [comment]
Back to Redis: https://github.com/NodeRedis/node-redis

**Comment by idowling1007** [comment]
Confirmed the updates are working. Closing the issue.
