### ISSUE TITLE
High - Reviewers can currently leave more than one review on a therapists account.

### ISSUE THREAD

**Issue by idowling1007** [idowling1007/therapy-reviews#60]
This should not be possible, as we need to be sure that someone is not going to the same therapist and posting multiple messages. 

There should a block in place that links the review to the reviewers login information, and stop them from leaving more than one review for the same person. In case a therapists spouse, or friends are trying to increase the rating fraudulently.

It should allow them to edit their original review, but not allow them to add a new one.

**Comment by KC135Q** [comment]
The code update will be able to check by social media account. So they can potentially leave a review using Google and then one using Facebook but they will not be able to leave multiple under the same social media account.

**Comment by idowling1007** [comment]
Hey @KC135Q - I tested this morning being logged in via Tamara's google account, and I was still able to leave multiple reviews on my profile

**Comment by idowling1007** [comment]
Hey @KC135Q  & @gitKendra I just checked on this issue just now (6/6/20 - 2:25pm), and I am still able to leave multiple reviews on accounts. I left 2 on My account using Tamara's login, and 2 on Dan's account. Can you have a check when you have a chance?

**Comment by idowling1007** [comment]
Confirmed that this is completed. Closing
